// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0RQow1yAj9Msflw708ihF1_BwW3rBays',
    appId: '1:476971893933:web:938c5608867d9fded93224',
    messagingSenderId: '476971893933',
    projectId: 'financeapp-f787f',
    authDomain: 'financeapp-f787f.firebaseapp.com',
    storageBucket: 'financeapp-f787f.firebasestorage.app',
    measurementId: 'G-GFGSLV9GXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYO_aPbVUQer94IHoThmSZ3B0psedwIMI',
    appId: '1:476971893933:android:5b7904bfd4b5992bd93224',
    messagingSenderId: '476971893933',
    projectId: 'financeapp-f787f',
    storageBucket: 'financeapp-f787f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfcVqrgJeS13AyXigDyPVhEG3YggRTpdw',
    appId: '1:476971893933:ios:ae9c2a536e4e2c33d93224',
    messagingSenderId: '476971893933',
    projectId: 'financeapp-f787f',
    storageBucket: 'financeapp-f787f.firebasestorage.app',
    iosBundleId: 'com.matheus.financeapp',
  );
}
